# Makefile for testing functions submitted with a main function
# It uses catch testing library
# Compile your program: make

#

#Variables
CFLAGS = -Wall -std=c++11
CC = g++

# Replace with your own file names.
a.out: indexing.cc index-tree.h
	$(CC) $(CFLAGS) indexing.cc -o a.out


clean:
	rm -rf a.out *.o 
